# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
