# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_music_name'),
        ('Website', '0002_auto_20171213_1238'),
    ]

    operations = [
    ]
